[package]
name = "ci_test"
version = "2.0.15"
authors = ["Angelos Gkountis <agelosbb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
