name: CI-build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: agkountis/rust:cmake

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - shell: bash
      run: |
        mkdir package
        cp target/release/ci_test package
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: executable
        path: ./package
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc --no-deps
