name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: agkountis/rust:cmake

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - shell: bash
      run: |
        mkdir package
        cp target/release/ci_test package
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: executable
        path: ./package
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc --no-deps

  release:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'
    steps:
      - name: Chekout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: |
          npm install @semantic-release/changelog @semantic-release/git @semantic-release/exec -D
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - shell: bash
        run: |
          cargo install cargo-bump
      - name: semrel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@15.10.6


